language: cpp
compiler: gcc
dist: xenial

before_install:
  # C++14
  - sudo add-apt-repository --yes ppa:ubuntu-toolchain-r/test
  - sudo apt-get update -qq
  # Codecov
  - sudo pip install codecov

install: 
  # C++14
  - sudo apt-get install googletest
  - sudo apt-get install -qq g++-7
  - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-7 90
  # Qt5
  - sudo apt-get install -qq libqt5webkit5-dev qtdeclarative5-dev
  - export QMAKE=/usr/lib/x86_64-linux-gnu/qt5/bin/qmake
  # Codecov
  - sudo update-alternatives --install /usr/bin/gcov gcov /usr/bin/gcov-5 90

before_script:
  - cd /usr/src
  - sudo mkdir build-gtest
  - cd build-gtest
  - sudo cmake ../googletest
  - make install

# Start virtual X server, from https://docs.travis-ci.com/user/gui-and-headless-browsers/
#before_script:
#  - "export DISPLAY=:99.0"
#  - "sh -e /etc/init.d/xvfb start"
#  - sleep 3 # give xvfb some time to start

script:
  - cd ..
  - mkdir build-debug-GenericDataBindingWithQt
  - cd build-debug-GenericDataBindingWithQt
  - qmake -qt=qt5 ../GenericDataBindingWithQt
  - make
  - pwd
  - ls
  - ls DataProvider
  - ls DataProvider/DataProviderTest
  - ls DataBinding
  - ls DataBinding/DataBindingTest
  - ls RequestData
  - ls RequestData/RequestDataTest
  
